language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  firefox: latest
  sauce_connect: true
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install -g bower polylint web-component-tester
- bower install
- polylint
script:
- xvfb-run wct
- if [ "${TRAVIS_PULL_REQUEST}" = "false"  ]; then wct -s 'default'; fi
env:
  global:
  - secure: p5eak1bvVPKJz67+2SEa0PM8LCk0Hegb4CR/M+VvtSxnHYNiP7Sc/f4wd7mvVfwd3rVJ8ppK7PDwyoUYmnmUmC2rj1d5ty6cWzd0AxGKaMqr58nVNPYeFWP77Caq9XzkzZYK2ZSgnmsoJhqR73D59o/FwE3fjojyCe9nUwaaEthpF1h4MoLGCQT6aXi9NLaoq4Gtb7QbgMsis3XpespIar1yfIDb7iu2PjSX+EKx3F1Cqc7bQ4+HOXe1vwRHM2/lWB7BcbthOhxrQOyAIOMXsQGj33Tj4XrXHEtcA+pZXE0pp3JRUE/X0sHi0qi4KUgwPhAfqB/6t7T7PKwWWW4+ywlRIk0DwlFVf6vwnXYvmVyuU2Ushsgsp43EY4IPrlynOxiguTU5EuEytpwMjvKJ1VRub71bm3dOWAzBDZ4iR6hEReQjj+e/8a/3KIRRoGhtW+PVMvgzUxazbDiqAMEV9ZfxDbx/GnIpwrcO3xptjZLrROyjZHK4ezd3w5QxJTbiQz3LEPbLRuSBZAH47eu+/YbeYqHgdkxDnLTtt3RBIO8wYOfvHvrKdjLshTM8c6I+5+SUZI7vZRcFaIUXcD1aU1aLDl6LdzjUHLjAUR1qNw46nvSw7CMg8UbftvzOumQ+9HCoQimCMrcqiyy9Btr8NSavxNv8cZbdhZPabjWopdo=
  - secure: 0W8wQnBgB2isCJ/Wmi9lqrrHq//Dyl3U+/3M5o4Lu6HhQaS/ULqMqP3oHyDRs0SqiMjFc7xsfo5YU+i6jXozeHU5pKnkAFwQkFqGayLZuA/e0/IRYGrwom6JvMvQuLIfoM9ybRtc2C6RIZGaPUEAc2nNQSQu/9zKHwZQGEBCDOcFInHA/qQTBS22SDwNYIgdaL42QvLI+VmJmwYcWilunBRw7m4ehuGRykC9hQJAfgyeSKlazQ59npm30lcBZCwnBM7/y5odlriymI28PL/VkTVGBjoRN0RVROXVDi+OTEUqfrQgDdYjWjVNB1neSMyI89kFVRrYAeAIlNdVPlEHbVJAkndXfW2NC8Pfedkf/gHw8pVq4ZVfrg1Tb8YJsICbMGegiC6wOfRv0FSYUx5/9KiJl2bVSF0DHQq1OAT7o+pzYYFotVsvW3OSq6TukhaHJ5v6Lp8dd+xjKVDvMRPHuBePdSCx/CUk59wCM/9nlwop6yGMJ6tCRsD5V95i6jNAo2WVg7xdyLOZu8TZqIolbx+8njziwLeWGn1H2IjKyGTu0+/sf8wscllH0g2bTBTcx1sK9ITGmwHO6Xin6MkoIx/Wk8IYw41VRKcb+kH0vV/F80UgD1z1h6KlEM2J4N8O1Whq0mmBTX/ng/2QzXL8c9TiZ3br2eycPbxTREmoPLU=
